spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: HTML5
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.11.107:3306/text?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
#mybatis配置
mybatis:
  #配置SQL映射文件路径
  mapper-locations: classpath:mapper/*.xml
  #配置别名
  #type-aliases-package: com.bs.dao.LoginMapper
  #驼峰命名
  #configuration:
    #map-underscore-to-camel-case: true